packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  argon2: true
  better-sqlite3: true
  esbuild: true
  puppeteer: true

onlyBuiltDependencies:
  - argon2
  - better-sqlite3
  - esbuild
  - puppeteer
