packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  argon2: set this to true or false
  better-sqlite3: set this to true or false
  esbuild: set this to true or false
  puppeteer: set this to true or false

onlyBuiltDependencies:
  - argon2
  - better-sqlite3
  - esbuild
  - puppeteer
